"""initial_schema_phase2

Revision ID: 6dc864d1ffb6
Revises: 
Create Date: 2026-05-20 05:18:59.791670
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '6dc864d1ffb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('table_name', sa.String(length=128), nullable=False, comment="The table that was mutated (e.g. 'research_sessions')."),
    sa.Column('record_id', sa.UUID(), nullable=False, comment='Primary key of the mutated record.'),
    sa.Column('action', sa.String(length=16), nullable=False, comment='Mutation type: INSERT | UPDATE | DELETE.'),
    sa.Column('changed_by', sa.String(length=256), nullable=True, comment='User or service identity that triggered the change. Nullable until auth is implemented.'),
    sa.Column('created_at', sa.String(), server_default='NOW()', nullable=False, comment='Timestamp of the audit event (UTC).'),
    sa.Column('previous_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot of field values BEFORE the mutation. Null for INSERT.'),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot of field values AFTER the mutation. Null for DELETE.'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='Correlation/request ID from the HTTP request that triggered the change.'),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary extra context (IP address, user-agent, feature flag states, etc.).'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_table_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_table('research_sessions',
    sa.Column('topic', sa.Text(), nullable=False, comment='The research query or topic submitted by the user.'),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False, comment='Current lifecycle status of the research session.'),
    sa.Column('result_summary', sa.Text(), nullable=True, comment='Final synthesized research summary. Populated on COMPLETED.'),
    sa.Column('result_token_count', sa.Integer(), nullable=True, comment='Token count of the final result. Used for billing/observability.'),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary session metadata (model config, user context, etc.).'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details if the session moved to FAILED state.'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sessions'))
    )
    op.create_index('ix_research_sessions_created_at', 'research_sessions', ['created_at'], unique=False)
    op.create_index('ix_research_sessions_status', 'research_sessions', ['status'], unique=False)
    op.create_table('execution_logs',
    sa.Column('session_id', sa.UUID(), nullable=False, comment='Parent research session.'),
    sa.Column('agent_role', sa.String(length=64), nullable=False, comment='The agent role executing this step (planner, researcher, etc.).'),
    sa.Column('step_name', sa.String(length=128), nullable=False, comment='Human-readable name for this execution step.'),
    sa.Column('step_order', sa.Integer(), nullable=True, comment='Ordinal position of this step within the session. Used for ordering.'),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False, comment='Step status: pending | running | completed | failed | skipped.'),
    sa.Column('message', sa.Text(), nullable=True, comment='Human-readable progress message or error detail.'),
    sa.Column('error_detail', sa.Text(), nullable=True, comment='Full exception trace or error context for failed steps.'),
    sa.Column('duration_ms', sa.Float(), nullable=True, comment='Wall-clock duration of this step in milliseconds.'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='Tokens consumed by LLM calls in this step (for cost tracking).'),
    sa.Column('step_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary step data: model params, source URLs, chunk counts, etc.'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], name=op.f('fk_execution_logs_session_id_research_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_logs'))
    )
    op.create_index(op.f('ix_execution_logs_session_id'), 'execution_logs', ['session_id'], unique=False)
    op.create_index('ix_execution_logs_session_id_order', 'execution_logs', ['session_id', 'step_order'], unique=False)
    op.create_index('ix_execution_logs_status', 'execution_logs', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('session_id', sa.UUID(), nullable=False, comment='Parent research session.'),
    sa.Column('url', sa.Text(), nullable=False, comment='Full URL of the fetched source.'),
    sa.Column('domain', sa.String(length=256), nullable=True, comment="Extracted domain for grouping/filtering (e.g. 'arxiv.org')."),
    sa.Column('title', sa.Text(), nullable=True, comment='Page title extracted from HTML.'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA-256 of raw content. Enables cross-session deduplication.'),
    sa.Column('fetch_status', sa.String(length=32), server_default='pending', nullable=False, comment='Fetch lifecycle: pending | fetching | fetched | failed | skipped.'),
    sa.Column('fetch_error', sa.Text(), nullable=True, comment="Error detail if fetch_status is 'failed'."),
    sa.Column('raw_token_count', sa.Integer(), nullable=True, comment='Estimated token count of raw fetched content (before chunking).'),
    sa.Column('summary_token_count', sa.Integer(), nullable=True, comment='Token count of the generated source summary.'),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='Number of content chunks produced from this source.'),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary source metadata: HTTP status, content-type, language, etc.'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], name=op.f('fk_sources_session_id_research_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index('ix_sources_content_hash', 'sources', ['content_hash'], unique=False)
    op.create_index(op.f('ix_sources_domain'), 'sources', ['domain'], unique=False)
    op.create_index(op.f('ix_sources_session_id'), 'sources', ['session_id'], unique=False)
    op.create_index('ix_sources_session_id_fetch_status', 'sources', ['session_id', 'fetch_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sources_session_id_fetch_status', table_name='sources')
    op.drop_index(op.f('ix_sources_session_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_domain'), table_name='sources')
    op.drop_index('ix_sources_content_hash', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_execution_logs_status', table_name='execution_logs')
    op.drop_index('ix_execution_logs_session_id_order', table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_session_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index('ix_research_sessions_status', table_name='research_sessions')
    op.drop_index('ix_research_sessions_created_at', table_name='research_sessions')
    op.drop_table('research_sessions')
    op.drop_index('ix_audit_logs_table_record', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
